googleapis/nodejs-tasks

.gitignore
=> style: .gitignore new line at EOF

package.json
=> fix: test-no-cover should timeout

.gitignore, CONTRIBUTORS, package.json, synth.py
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> synth script checkin

.circleci/config.yml, src/index.js, src/v2beta2/cloud_tasks_client.js, synth.py
This may break the next time gapic runs, but we can deal with that then :)  Resolves #58
=> fix: udpate require statements in docs

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release nodejs-tasks v0.1.1

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @google-cloud/tasks v0.2.1

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @google-cloud/tasks v0.2.2

samples/createTask.js
Fixes googleapis/google-cloud-node#2869 (it's a good idea to open an issue first for discussion)
Fixes https://github.com/googleapis/nodejs-tasks
=> docs(samples): updated samples code to use async await

CHANGELOG.md, package.json, samples/package.json
This pull request was generated using releasetool.
=> Release @google-cloud/tasks v0.3.0

README.md
Fixes #175 
[Preview](https://github.com/callmehiphop/nodejs-tasks/blob/dg--175/README.md)
The README was kind of stale, I've made some minor edits to model it after our other repos.
=> docs: update README to include samples

.gitignore, protos/google/cloud/tasks/v2/cloudtasks.proto, protos/google/cloud/tasks/v2/queue.proto, protos/google/cloud/tasks/v2/target.proto, protos/google/cloud/tasks/v2/task.proto, samples/listQueues.js, src/index.js, src/v2/cloud_tasks_client.js, src/v2/cloud_tasks_client_config.json, src/v2/doc/google/cloud/tasks/v2/doc_cloudtasks.js, src/v2/doc/google/cloud/tasks/v2/doc_queue.js, src/v2/doc/google/cloud/tasks/v2/doc_target.js, src/v2/doc/google/cloud/tasks/v2/doc_task.js, src/v2/doc/google/iam/v1/doc_iam_policy.js, src/v2/doc/google/iam/v1/doc_policy.js, src/v2/doc/google/protobuf/doc_any.js, src/v2/doc/google/protobuf/doc_duration.js, src/v2/doc/google/protobuf/doc_empty.js, src/v2/doc/google/protobuf/doc_field_mask.js, src/v2/doc/google/protobuf/doc_timestamp.js, src/v2/doc/google/rpc/doc_status.js, src/v2/index.js, synth.metadata, synth.py, test/gapic-v2.js
This adds the `v2` version of the Tasks API, and makes it the default.
=> feat: add v2 of the tasks API

samples/README.md, samples/app.yaml, samples/createHttpTask.js, samples/createQueue.js, samples/createTask.js, samples/deleteQueue.js, samples/server.js, samples/test/test.samples.js
Closed PR#187 due to git errors.
=> docs(samples): Add HTTP Push Queue Sample

.kokoro/samples-test.sh, samples/Dockerfile, samples/createHttpTaskWithToken.js, samples/package.json, samples/test/test.samples.js
Adding Dockerfile to deploy to Cloud Run and sample with OIDC token for authentication.
=> docs(samples): Add HTTP Task Sample with Authentication Token

.kokoro/samples-test.sh, samples/test/test.samples.js
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> docs(samples): Update service account for tests

.repo-metadata.json, README.md, package.json, protos/google/cloud/tasks/v2/cloudtasks.proto, protos/google/cloud/tasks/v2/queue.proto, protos/google/cloud/tasks/v2/target.proto, protos/google/cloud/tasks/v2/task.proto, protos/google/cloud/tasks/v2beta3/cloudtasks.proto, protos/google/cloud/tasks/v2beta3/target.proto, samples/README.md, samples/quickstart.js, samples/test/test.samples.js, src/v2/cloud_tasks_client.js, src/v2/doc/google/cloud/tasks/v2/doc_cloudtasks.js, src/v2/doc/google/cloud/tasks/v2/doc_target.js, src/v2beta3/cloud_tasks_client.js, src/v2beta3/doc/google/cloud/tasks/v2beta3/doc_target.js, synth.metadata
along with bumping to 1.0.0, update docs to reflect ga status.
=> docs: generate docs for ga release

samples/createHttpTask.js, samples/createHttpTaskWithToken.js, samples/createTask.js, samples/package.json, samples/test/test.samples.js
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> docs(samples): Update metadata and arguments

samples/createHttpTask.js
- Simplifies Tasks creation sample via object destructuring and increased identifier locality.
- Pairs `request` with `response` for easier reading.
=> feat: Simplify Tasks Create Sample

samples/createHttpTaskWithToken.js
Fixes no particular issue. Just some minor style changes.
=> refactor: Simplify cloud_tasks_create_http_task_with_token

samples/createTask.js
Small style fix for tasks_quickstart.
=> refactor: style fixes for tasks_quickstart

.jsdoc.js, .prettierrc.js, package.json, protos/protos.js, protos/protos.json, synth.metadata, synth.py, test/gapic_cloud_tasks_v2.ts, test/gapic_cloud_tasks_v2beta2.ts, test/gapic_cloud_tasks_v2beta3.ts
Run the latest version of the generator, update google-gax, update gts, and remove direct dependencies on eslint.
=> fix: remove eslint, update gax, fix generated protos, run the generator

.gitattributes, .gitignore
fix window lint
set protos/ as linguist-generated field
=> build: add gitattribute
